sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t dorrypizza/dnsmasq-rpi .
# test image
- docker images
# push image
