sudo: required
services:
- docker
language: bash
dist: trusty

before_install:
    - sudo apt-get update
    - sudo apt-get install qemu-system-arm wget xz-utils sshpass

install:
    - wget "https://super-secret-location.com/2015-11-21-raspbian-jessie-lite.img.xz"
    - unxz "2015-11-21-raspbian-jessie-lite.img.xz"
    - git clone https://github.com/polaco1782/raspberry-qemu.git

before_script:
    - qemu-system-arm -kernel raspberry-qemu/kernel-qemu -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw" -net user,hostfwd=tcp::10022-:22 -net nic -display none -hda 2015-11-21-raspbian-jessie-lite.img &

script:
# build image
- docker build -t dorrypizza/dnsmasq-rpi .
# test image
- docker images
# push image

