sudo: required
services:
- docker
language: bash
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y --no-install-recommends qemu-user-static binfmt-support
  - sudo update-binfmts --display qemu-arm
script:
# build image
- docker build -t dorrypizza/dnsmasq-rpi .
# test image
- docker images
# push image
